### ISSUE TITLE
Consider renaming CR kind to "KnativeServing"

### ISSUE THREAD

**Issue by rhuss** [openshift-knative/knative-serving-operator#17]
I believe, "Install" as a name for the CR is too generic. Currently, its also used by eventing (and Tekton pipeline install operator).

I suggest to rename it to "KnativeServing" and "KnativeEventing" for the corresponding eventing operator.

Why ?

* `kubectl get install` would need to be always fully qualified with the API group if more than one "install" CR is present (`kubectl get installs.serving.knative.de`)
* "install" is too generic and is more a verb than a noun like CRs typically are (therefore that singular/plural thing in the CRD definition)
* Other products install operators like for Prometheus or Etcd also call their CR after the product (i.e. "Prometheus" and "Etcd", respectively)
* Its easier to understand a `kind: KnativeServing` alone then checking the `apiVersion: serving.knative.dev/v1alpha1` always together with the `kind`.

If we want to change that name, we should do it ASAP, i.e. before going to upstream with it.

**Comment by jcrossley3** [comment]
I feel you on this. We have an even larger debate about the group name, so we may as well change them all at the same time. I initially considered `KnativeServing` but thought it was redundant when fully-qualified by its group name: `install.serving.knative.dev` sounded better than `knativeserving.serving.knative.dev`, but if we change the domain to something like `openshift.io` that would make `knativeserving.knative.openshift.io` a little less redundant. :)

FWIW, there are short names for serving (ksi), eventing (kei), and build (kbi) -- see the pattern? -- to avoid the naming conflict: `kubectl get ksi`

**Comment by rhuss** [comment]
Very good point and having shortcuts is a great help.

It probably all boils down, whether the UX should use `kind` or `apiVersion` as primary key (better, api-group then with the `kind` as kind of a sub-key).

My gut feeling is, that people except to be able to figure out the type of a CRD by looking at the `kind` alone. One indicator e.g. is how CRDs are presented when listed and how they are ordered.

This is an extract of a 4.1 OCP cluster's CRD + Knative:

![image](https://user-images.githubusercontent.com/99080/58236592-7f16eb00-7d43-11e9-981c-35e8a76d815a.png)

The default sorting is alphabetically on the first column. At the moment there are some _install_ kind of CRDs (with variations like `InstallPlan` or `installation`), but most of the other CRDs are trying to be unique on the kind-name (like `zipkin`). If one sort on the `GROUP` column, it's also not easy to spot the `serving.knative.dev` install resource if looking for "knative" (because its starts with 'serving'). Also eventing and build would be in total different regions. Well I guess this more a  weaker argument ;-)

Wells, at the end its also ends up as a matter of taste, whether a kind should be identifiable standalone or only together with its API group. The good thing: We are already using an uppercase for the the first letter. Istio does not and that totally confuses the sorting in the dev-console ;-)

![image](https://user-images.githubusercontent.com/99080/58237175-c3ef5180-7d44-11e9-99eb-ab158c83e994.png)

**Comment by jcrossley3** [comment]
After discussions here and with others (@bbrowning @markusthoemmes @pmorie), I'm inclined to go with a kind of `KnativeServing` and a group of `not-knative.dev`. We can stay with that until we move out of our `alpha` apiVersion. Work for you?

**Comment by rhuss** [comment]
Cool, perfectly fine for me. 'happy to help if there is something I can do.

**Comment by bbrowning** [comment]
Literally a group of `not-knative.dev`?

**Comment by jcrossley3** [comment]
> Literally a group of `not-knative.dev`?

I think that was the consensus, yeah. Got a better idea?

**Comment by rhuss** [comment]
Maybe something like "incubator.knative.dev" or "incubator-knative.dev" ? Or 'extra-knative.dev' ? 'ext-knative.dev' ? But I'm fine with 'not-knative.dev', too, as a reminder that it needs to be renamed anyway ? Should this be negotiated with the uptream community ?
