### ISSUE TITLE
RBAC issue on OpenShift (cannot list resource "routes")

### ISSUE THREAD

**Issue by a-roberts** [openshift-knative/knative-serving-operator#71]
I realise this is an obsolete repo now but I'm looking to test 0.8.1 of Knative serving installed through an operator on OpenShift 4.2 - and I think this is the best place to get started as the 1.0.0 serverless operator is pulling in 0.7.1.

So I checked out the latest tag here (see my notes at https://github.com/a-roberts/openshift42/blob/master/README.md) and see

```
adams-mbp:knative-serving-operator aroberts$ kgp
NAME                                           READY     STATUS             RESTARTS   AGE
knative-serving-operator-d5dd55cf8-s2zfg       0/1       CrashLoopBackOff   5          5m57s
```

Logs show

```
{"level":"error","ts":1571330062.425114,"logger":"cmd","msg":"","error":"routes.route.openshift.io is forbidden: User \"system:serviceaccount:openshift-pipelines:knative-serving-operator\" cannot list resource \"routes\"
```

This is even with a modification to include
```
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs:  ["get", "list", "update", "delete", "create", "patch"]
```

for the  clusterrole knative-serving-operator. Any ideas please? I'm confident my RBAC addition's pretty good but it can't be - or something else is stopping this?

**Comment by bbrowning** [comment]
As you mentioned, this repo is obsolete and we're working to move as much of the Serving operator stuff to upstream Knative as possible. The closet thing to a newer version of our OpenShift Serverless Operator that's available in OCP4 consoles would be the master branch of https://github.com/openshift-knative/serverless-operator . You'll see it has an unreleased Serverless Operator 1.1.0 that includes Knative Serving 0.8.1 at https://github.com/openshift-knative/serverless-operator/blob/master/olm-catalog/serverless-operator/serverless-operator.v1.1.0.clusterserviceversion.yaml .

I'd recommend you stick to released versions of the Serverless operator on OpenShift 4 cluster. Those are the only versions Red Hat is committed to supporting as a Technology Preview (https://access.redhat.com/support/offerings/techpreview). Or, if you don't want to use product releases, then the upstream Knative Serving Operator (https://github.com/knative/serving-operator/) is next-best thing to use.

**Comment by jcrossley3** [comment]
That `openshift-pipelines` namespace in your error may be a clue. I'm curious why you had to modify the `ClusterRole` since it's effectively `cluster-admin` already: https://github.com/openshift-knative/knative-serving-operator/blob/openshift-knative/v0.8.1-1.1.0-05/deploy/role.yaml#L56-L63

**Comment by bbrowning** [comment]
I'm closing the issue as this isn't the proper place to try and support this. I'd reiterate that you should either run a released version of the OpenShift Serverless operator and seek support for any bugs you find via the typical Red Hat customer channels OR run the upstream Knative Serving operator and work in that community to identify and resolve any issues.

If you feel strongly that someone within Red Hat should support this specific need, then that's a separate conversation we should have elsewhere.

**Comment by a-roberts** [comment]
@bbrowning @jcrossley3 thanks for the prompt responses, the Serverless Operator 1.1.0 sounds like exactly what I'm after then (I stumbled upon *this* as being the place for latest 0.8.x. code and 0.9 was my next thing to look) - I'll give that a go and use the repository you've mentioned for anything else, cheers 😄
